name: Vercel Production Deployment

on:
  push:
    branches:
      - develop  

jobs:
  Deploy-Production:
    # PREVINA execuções concorrentes
    concurrency: 
      group: production-deploy
      cancel-in-progress: true
    
    runs-on: ubuntu-latest
    
    env:
      VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        working-directory: ./podologos
        run: npm ci
      
      - name: Install Vercel CLI
        working-directory: ./podologos
        run: npm install --save-dev vercel
      
      - name: Pull Vercel Environment Information
        working-directory: ./podologos
        run: npx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Build Project Artifacts
        working-directory: ./podologos
        run: npx vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Deploy to Production
        working-directory: ./podologos
        run: npx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}